[package]
authors = ["Mixxy3k"]
edition = "2021"
readme = "README.md"
name = "stm32"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.4"
cortex-m-rt = { version = "0.7.1", features = ["device"] }
panic-halt = "0.2.0"
stm32f3xx-hal = { version = "0.9.0", features = ["ld", "rt", "stm32f303xc"] }
